//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppFinal.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AppFinal.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap kisspng_ape_escape_movement_camp_europe_exit_arrow_left_exit_png_transparent_images_13_16_x_16_carwa_5cfb09b21d4c61_08834362155995589012 {
            get {
                object obj = ResourceManager.GetObject("kisspng_ape_escape_movement_camp_europe_exit_arrow_left_exit_png_transparent_imag" +
                        "es_13_16_x_16_carwa_5cfb09b21d4c61_08834362155995589012", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap kisspng_computer_icons_download_icon_svg_add_5ab055e47b53b7_3576841815215057645052 {
            get {
                object obj = ResourceManager.GetObject("kisspng_computer_icons_download_icon_svg_add_5ab055e47b53b7_357684181521505764505" +
                        "2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap kisspng_computer_icons_floppy_disk_download_save_button_5acb80653f6145_2305909515232861172596 {
            get {
                object obj = ResourceManager.GetObject("kisspng_computer_icons_floppy_disk_download_save_button_5acb80653f6145_2305909515" +
                        "232861172596", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap kisspng_computer_icons_scalable_vector_graphics_apple_icon_edit_png_icon_blue_pencil_5ab065d43019b7_7432604215215098441971 {
            get {
                object obj = ResourceManager.GetObject("kisspng_computer_icons_scalable_vector_graphics_apple_icon_edit_png_icon_blue_pen" +
                        "cil_5ab065d43019b7_7432604215215098441971", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap kisspng_computer_icons_scalable_vector_graphics_illustrati_font_shanchu_svg_png_icon_free_download_4_928_5c5c6c88cf1a00_0493373015495609688483 {
            get {
                object obj = ResourceManager.GetObject("kisspng_computer_icons_scalable_vector_graphics_illustrati_font_shanchu_svg_png_i" +
                        "con_free_download_4_928_5c5c6c88cf1a00_0493373015495609688483", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap kisspng_computer_icons_scalable_vector_graphics_symbol_cli_plus_sign_5aaad88d6ee9a1_3132124515211459974543 {
            get {
                object obj = ResourceManager.GetObject("kisspng_computer_icons_scalable_vector_graphics_symbol_cli_plus_sign_5aaad88d6ee9" +
                        "a1_3132124515211459974543", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap kisspng_computer_icons_synchronization_encapsulated_postsc_update_button_5ac49263b3fc56_6736388715228319717372 {
            get {
                object obj = ResourceManager.GetObject("kisspng_computer_icons_synchronization_encapsulated_postsc_update_button_5ac49263" +
                        "b3fc56_6736388715228319717372", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap kisspng_health_care_computer_icons_information_business_cancel_button_5abbe5f13cf428_3676993215222635372497 {
            get {
                object obj = ResourceManager.GetObject("kisspng_health_care_computer_icons_information_business_cancel_button_5abbe5f13cf" +
                        "428_3676993215222635372497", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap kisspng_service_product_company_customer_research_and_deve_5b7616e33de553_2255723215344657632535 {
            get {
                object obj = ResourceManager.GetObject("kisspng_service_product_company_customer_research_and_deve_5b7616e33de553_2255723" +
                        "215344657632535", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
